Add general testing section
infinum/frontend-handbook pull request #110
Opened 2021-04-16 08:11 UTC by mislavmiocevic

2021-04-16 08:14 UTC, mislavmiocevic commented
Added new PR with all latest changes and correct file location.

2024-02-12 11:39 UTC, MarinTeskera requested changes
I left some grammatical suggestions to make the chapter easier to read.

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +What is common for them is, as we said already, that they are writing code for tests.
```suggestion
What's common for them, as we said already, is that they are writing code for tests.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +simple failing test and as smallest code possible to pass that test.
```suggestion
simple failing test and smallest code possible to pass that test.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Let's say we want to develop calculator function that allows addition, subtraction, multiplication and
```suggestion
Let's say we want to develop a calculator function that allows addition, subtraction, multiplication and
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +calculator function should take 3 arguments: two numbers and operation type.
```suggestion
The calculator function should take 3 arguments: two numbers and operation type.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +We write some code to throw error if calculator called empty.
```suggestion
We write some code to throw an error if calculator was called empty.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +We write code to throw error if there is 0, 1, 2, 4 or more arguments.
```suggestion
We write code to throw an error if there is 0, 1, 2, 4 or more arguments.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +We see opportunity to refactor both in code and test.
```suggestion
We see an opportunity to refactor both in code and test.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +There is check for empty and for exactly three arguments.
```suggestion
There is a check for empty and for exactly three arguments.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +We can leave them both, or remove empty check since it is covered by this second test.
```suggestion
We can leave them both, or remove the empty check since it is covered by this second test.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Let's remove empty check to clean code.
```suggestion
Let's remove the empty check to clean code.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +We test that string is correct value which can be 'ADD', 'SUBTRACT' and so on - whatever our
```suggestion
We test that the string is correct value which can be 'ADD', 'SUBTRACT' and so on - whatever our
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +You might be yelling 'Where is calculation implementation!'.
```suggestion
You might be yelling 'Where is the calculation implementation!'.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +TDD is excellent technique for catching bugs in the start.
```suggestion
TDD is an excellent technique for catching bugs in the start.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +You do not have implementation at the moment, just criteria for what should it be.
```suggestion
You do not have implementation at the moment, just criteria for what it should be.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Just, how it should be used, at the moment, not later.
```suggestion
Just how should it be used at the moment, not later.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Let's get back to calculator function and second test.
```suggestion
Let's get back to the calculator function and its second test.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Skipping first since we removed it.
```suggestion
Skipping the first one since we removed it.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +Green phase is where you finally can make implementation and make your test passing - green.
```suggestion
Green phase is where you can finally make the implementation and make your test passing - green.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +And it is test not tests since you should at this moment concentrate on new one and not old tests.
```suggestion
And it is test not tests since you should, at this moment, concentrate on the new one and not the old tests.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +And finally refactor phase (also known as yellow phase) where you remove code duplication, clean a bit, make variable names
```suggestion
And finally refactor phase (also known as yellow phase) where you remove code duplication, clean up a bit, make variable names
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +If something fails, go back to where you have been before.
```suggestion
If something fails, go back to where you were before.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +This is as we said simplified version of TDD.
```suggestion
This is, as we said, a simplified version of TDD.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +And then you repeat all steps for new test.
```suggestion
And then you repeat all steps for further tests.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +There are some "laws" created by community and us which need to be followed, but rest is on you and your team.
```suggestion
There are some "laws" created by the community and us which need to be followed, but the rest is on you and your team.
```

2024-02-12 11:39 UTC, MarinTeskera commented on Testing.md
> +4. Pre-commit test execution is must
```suggestion
4. Pre-commit test execution is a must
```

2024-05-21 08:45 UTC, andreicek approved these changes

2024-05-21 08:46 UTC, kristijanbambir approved these changes

2024-05-21 08:55 UTC, DarkoKukovec approved these changes

2024-05-21 08:55 UTC, merged