#347 Document NextJS font optimization
infinum/frontend-handbook pull request #156
Opened 2022-04-01 14:26 UTC by mislavmiocevic

Task: https://app.productive.io/1-infinum/tasks/task/2306288?filter=LTE%3D

2022-05-10 14:15 UTC, kristijanbambir requested changes
Do not split long lines yourself, especially in the middle of sentences.

2022-05-18 08:33 UTC, mislavmiocevic commented
@kristijanbambir the changes are added.
@isBatak the styling is fixed.

https://beta.infinum.com/handbook/frontend/react/recipes/nextjs-font-optimization

![beta infinum com_handbook_frontend_react_recipes_nextjs-font-optimization](https://user-images.githubusercontent.com/67387665/168995044-c3c8ce94-edec-4e6c-9705-7b7192892f2a.png)

2022-05-18 10:29 UTC, isBatak approved these changes

2022-05-18 14:05 UTC, kristijanbambir approved these changes

2022-05-18 14:10 UTC, merged