Update testing chapter
infinum/frontend-handbook pull request #163
Opened 2022-05-18 10:25 UTC by danijelbuhin

- Updated setup section
- Added naming convention
- Added events section
- Remove act usage

2022-05-18 11:27 UTC, isBatak approved these changes

2022-05-19 09:43 UTC, kristijanbambir requested changes

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +    expect(screen.(username)).toBeDefined();
```suggestion
    expect(screen.getByText(username)).toBeDefined();
```

As we talked in person, please add a paragraph on using screen over destructuring the render method return object.

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +If any part of your test is preforming the state update, that action needs to be wrapped into `waitFor`.
```suggestion
If any part of your test is performing the state update, that action needs to be wrapped into `waitFor`.
```

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +For simulating an event, we use `@testing-library/user-event` library.
```suggestion
For simulating an event, we use the `@testing-library/user-event` library.
```

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +In this page example we should test all three states of the page component. To do that we should mock `<ErrorPage>`, `<LoadingPage>` and `<UserTemplate>` and check if it's rendered based on fetcher r
```suggestion
In this page example we should test all three states of the page component. To do that we should mock `<ErrorPage>`, `<LoadingPage>` and `<UserTemplate>` and check if it's rendered based on the fetcher response.
```

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +To use swr in your tests, add `SWRConfig` to your `AllProviders` mock with following setup (note: your cases could require more customization):
```suggestion
To use SWR in your tests, add `SWRConfig` to your `AllProviders` mock with the following setup (note: your cases could require more customization):
```

2022-05-19 09:43 UTC, kristijanbambir commented on React/Testing best practices.md
> +With this setup, we are sure that each component we're testing will have it's own cache, so we don't have to manually clear cache before each test.
```suggestion
With this setup, we are sure that each component we're testing will have its own cache, so we don't have to manually clear the cache before each test.
```

2022-05-20 08:20 UTC, kristijanbambir approved these changes

2022-05-20 08:20 UTC, kristijanbambir commented on React/Testing best practices.md
> +To see more info about [why you should use screen](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen), and other common mistakes in RTL usage, please refer to th
```suggestion
To see more info about [why you should use screen](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen), and other common mistakes in RTL usage, please refer to [Kent's](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library) blog post.
```

2022-05-20 08:40 UTC, merged