Add naming convention table
infinum/frontend-handbook pull request #180
Opened 2022-10-13 09:00 UTC by isBatak

2022-10-13 11:08 UTC, kristian240 requested changes
You are adding a new chapter, you also need to update the `chapters.yaml` file.

2022-10-13 11:08 UTC, kristian240 commented on React/Naming Cheatsheet.md
> +## Naming Cheatsheet
We don't need a root heading, handbook will use name of the file as the first heading. We can remove this and change all other levels to `level - 1`. E.g., `### Naming Components -> ## Naming Components`.

2022-10-13 18:49 UTC, fvoska commented
I think we could move this to some framework-agnostic part, this makes sense for Angular as well

2022-10-14 09:06 UTC, isBatak commented
> I think we could move this to some framework-agnostic part, this makes sense for Angular as well
@fvoska I was thinking the same thing, but...
What should I do with the **Note** part? 
Do you have something similar to polymorphic components in Angular?

2022-10-28 12:38 UTC, isBatak commented on Naming Cheat Sheet.md
> +high context (HC)? + low context? (LC)? + base + part? + suffix?
```suggestion
high context (HC)? + low context (LC)? + base + part? + suffix?
```

2023-01-04 09:33 UTC, fvoska approved these changes

2023-01-04 09:34 UTC, fvoska commented
@isBatak this has been opened for a while. I am fine with the proposal, so if there are no additional comments from others, I think we can merge.

2023-01-04 11:08 UTC, isBatak commented
@fvoska thx, let me just check it on staging one more time

2023-01-04 13:17 UTC, merged